In [27]:
import pandas as pd
# Đọc dữ liệu từ tập tin CSV
df = pd.read_csv('https://drive.google.com/uc?id=11Ibd34CRcY9suKnpAFlWvy8o4-Dr5IPL')

In [28]:
df

     Outlook Temperature Humidity  Wind speed Play cricket
0      Sunny         NaN     High         4.0           No
1      Sunny         NaN     High        20.0           No
2   Overcast         Hot     High         6.0          Yes
3       Rain        Mild     High         2.0          Yes
4       Rain        Cool   Normal         7.0          Yes
5       Rain         NaN   Normal         NaN           No
6   Overcast        Cool   Normal        22.0          Yes
7      Sunny         NaN     High         4.0           No
8      Sunny        Cool   Normal         5.0          Yes
9       Rain        Mild   Normal         6.0          Yes
10     Sunny        Mild   Normal         NaN          Yes
11  Overcast        Mild     High         2.0          Yes
12  Overcast         NaN   Normal         8.0          Yes
13      Rain        Mild     High        18.0           No

### **Thay toàn bộ giá trị null bằng giá trị trung bình của cột**


---

Cú pháp: s.fillna(s.mean())

In [29]:
# Xử lý cột Temperature
temp_max = df['Temperature'].value_counts().idxmax()  # Tần số xuất hiện nhiều nhất
df['Temperature'].fillna(temp_max, inplace=True)     # Điền giá trị thiếu bằng tần số max

# Điền giá trị trung vị cho các giá trị thiếu trong cột "Wind speed"
# Xử lý cột Wind Speed
wind_median = df['Wind speed'].median()               # Trung vị
df['Wind speed'].fillna(wind_median, inplace=True)    # Điền giá trị thiếu bằng trung vị
df

     Outlook Temperature Humidity  Wind speed Play cricket
0      Sunny        Mild     High         4.0           No
1      Sunny        Mild     High        20.0           No
2   Overcast         Hot     High         6.0          Yes
3       Rain        Mild     High         2.0          Yes
4       Rain        Cool   Normal         7.0          Yes
5       Rain        Mild   Normal         6.0           No
6   Overcast        Cool   Normal        22.0          Yes
7      Sunny        Mild     High         4.0           No
8      Sunny        Cool   Normal         5.0          Yes
9       Rain        Mild   Normal         6.0          Yes
10     Sunny        Mild   Normal         6.0          Yes
11  Overcast        Mild     High         2.0          Yes
12  Overcast        Mild   Normal         8.0          Yes
13      Rain        Mild     High        18.0           No

In [30]:
transformed_data = pd.get_dummies(df[["Outlook","Temperature","Humidity","Wind speed"]])
transformed_data

,Wind speed,Outlook_Overcast,Outlook_Rain,Outlook_Sunny,Temperature_Cool,Temperature_Hot,Temperature_Mild,Humidity_High,Humidity_Normal
0,4.0,0,0,1,0,0,1,1,0
1,20.0,0,0,1,0,0,1,1,0
2,6.0,1,0,0,0,1,0,1,0
3,2.0,0,1,0,0,0,1,1,0
4,7.0,0,1,0,1,0,0,0,1
5,6.0,0,1,0,0,0,1,0,1
6,22.0,1,0,0,1,0,0,0,1
7,4.0,0,0,1,0,0,1,1,0
8,5.0,0,0,1,1,0,0,0,1
9,6.0,0,1,0,0,0,1,0,1
10,6.0,0,0,1,0,0,1,0,1
11,2.0,1,0,0,0,0,1,1,0
12,8.0,1,0,0,0,0,1,0,1
13,18.0,0,1,0,0,0,1,1,0

In [31]:
x_data = transformed_data.values
y_data = df["Play cricket"].values

In [32]:
from sklearn.model_selection import train_test_split
x_data_train, x_data_test, y_data_train, y_data_test = train_test_split(x_data, y_data,test_size=0.2,random_state=1 )

## Decision Tree
- **max_depth**: là một tham số kiểm soát độ sâu của cây. Nó xác định số lượng tối đa các nút con được phép trong một nút trên cây. Nếu max_depth quá lớn, mô hình sẽ quá phức tạp và có khả năng overfitting cao, ngược lại, nếu max_depth quá nhỏ, mô hình sẽ quá đơn giản và có khả năng underfitting cao.
- **min_samples_leaf**: là một tham số kiểm soát số lượng mẫu tối thiểu được yêu cầu để một nút có thể trở thành lá. Tham số này giúp kiểm soát độ sâu của cây và tránh tình trạng overfitting. Nếu min_samples_leaf quá nhỏ, mô hình sẽ quá phức tạp và có khả năng overfitting cao, ngược lại, nếu min_samples_leaf quá lớn, mô hình sẽ quá đơn giản và có khả năng underfitting cao.

## SVM
- **kernel**: là một hàm toán học dùng để chuyển đổi dữ liệu từ không gian gốc sang không gian mới để dữ liệu có thể phân chia tuyến tính hoặc phi tuyến. Có nhiều loại kernel khác nhau, trong đó kernel tuyến tính (linear), polynomial (poly), Gaussian RBF (rbf), và sigmoid là những kernel phổ biến nhất.
- **C**: là một tham số điều khiển sự phân chia của mô hình. Tham số này xác định độ lớn của các margin và giúp kiểm soát việc overfitting hoặc underfitting. Càng lớn thì mô hình càng phức tạp và có khả năng overfitting cao, ngược lại thì mô hình càng đơn giản và có khả năng underfitting cao.

In [33]:

from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# SVM
# Tìm các giá trị tốt nhất cho các tham số kernel và C
best_svm = None
best_svm_score = 0
for kernel in ['linear', 'poly', 'rbf', 'sigmoid']:
    for C in [0.1, 1, 10, 100]:
        svm = SVC(kernel=kernel, C=C)
        svm.fit(x_data_train, y_data_train)
        score = accuracy_score(y_data_test, svm.predict(x_data_test))
        if score > best_svm_score:
            best_svm = svm
            best_svm_score = score
print("Best SVM: ", best_svm)
print("SVM accuracy score: ", best_svm_score)

# Decision Tree
# Tìm các giá trị tốt nhất cho các tham số max_depth và min_samples_leaf
best_dt = None
best_dt_score = 0
for max_depth in [2, 3, 4, 5]:
    for min_samples_leaf in [1, 2, 3, 4]:
        dt = DecisionTreeClassifier(max_depth=max_depth, min_samples_leaf=min_samples_leaf)
        dt.fit(x_data_train, y_data_train)
        score = accuracy_score(y_data_test, dt.predict(x_data_test))
        if score > best_dt_score:
            best_dt = dt
            best_dt_score = score
print("Best Decision Tree: ", best_dt)
print("Decision Tree accuracy score: ", best_dt_score)

Best SVM:  SVC(C=100, kernel='sigmoid')
SVM accuracy score:  1.0
Best Decision Tree:  DecisionTreeClassifier(max_depth=2, min_samples_leaf=3)
Decision Tree accuracy score:  0.6666666666666666